version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 3001
    ports:
      - 3001:3001
    command: dev
    volumes:
      - .:/app
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 27017
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
      - 27017:27017
